-- First, ensure we have at least one artist
INSERT INTO artists (name, bio) VALUES
  ('Various Artists', 'Various artists from around the world')
ON CONFLICT DO NOTHING;

-- Get the artist id
DO $$
DECLARE
  artist_uuid UUID;
BEGIN
  SELECT id INTO artist_uuid FROM artists WHERE name = 'Various Artists' LIMIT 1;
  
  IF artist_uuid IS NULL THEN
    INSERT INTO artists (name) VALUES ('Various Artists') RETURNING id INTO artist_uuid;
  END IF;

  -- Insert all tracks (replace audio_url with actual storage paths)
  INSERT INTO tracks (title, artist_id, genre_id, duration, audio_url, plays) VALUES
  ('About You', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 210, 'About_You.mp3', 1000),
  ('Akhiyaan Gulaab', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 180, 'Akhiyaan_Gulaab_From_Teri_Baaton_Mein_Aisa_Uliha_Jiya.mp3', 900),
  ('Alibi', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 150, 'Alibi_with_Pabllo_Vittar_Yseult.mp3', 800),
  ('Apna Bana Le', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 240, 'Apna_Bana_Le.mp3', 2000),
  ('Apocalypse', artist_uuid, (SELECT id FROM genres WHERE name = 'Electronic'), 280, 'Apocalypse.mp3', 1500),
  ('BABYDOLL', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 170, 'BABYDOLL.mp3', 1200),
  ('Baarish', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 220, 'Baarish.mp3', 1100),
  ('Back to the Old House', artist_uuid, (SELECT id FROM genres WHERE name = 'Rock'), 190, 'Back_to_the_Old_House_2011_Remaster.mp3', 950),
  ('Banjaara', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 250, 'Banjaara.mp3', 1800),
  ('Beggin''', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 200, 'Beggin.mp3', 1600),
  ('Brooklyn Baby', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 230, 'Brooklyn_Baby.mp3', 1400),
  ('Can''t Help Falling In Love', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 210, 'Cant_Help_Falling_In_Love_with_The_Royal_Philharmonic_Orchestra.mp3', 2200),
  ('Co2', artist_uuid, (SELECT id FROM genres WHERE name = 'Electronic'), 160, 'Co2.mp3', 1000),
  ('Coffee', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 150, 'Coffee.mp3', 1300),
  ('Confess Your Love', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 155, 'Confess_Your_Love.mp3', 900),
  ('Cupid', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 180, 'Cupid.mp3', 2500),
  ('Dandelions', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 210, 'Dandelions.mp3', 3000),
  ('Die For You', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 230, 'Die_For_You.mp3', 2800),
  ('Duniyaa', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 200, 'Duniyaa_From_Luka_Chuppi.mp3', 1500),
  ('Enna Sona', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 210, 'Enna_Sona.mp3', 1200),
  ('Espresso', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 175, 'Espresso.mp3', 2700),
  ('Fade Into You', artist_uuid, (SELECT id FROM genres WHERE name = 'Rock'), 290, 'Fade_Into_You.mp3', 1100),
  ('Fairytale', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 190, 'Fairytale.mp3', 950),
  ('Favorite', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 160, 'Favorite.mp3', 850),
  ('Finding Her', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 200, 'Finding_Her.mp3', 750),
  ('Good For You', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 220, 'Good_For_You.mp3', 1300),
  ('Gulabi Aankhen', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 200, 'Gulabi_Aankhen.mp3', 1700),
  ('Heartbreak Anniversary', artist_uuid, (SELECT id FROM genres WHERE name = 'R&B'), 195, 'Heartbreak_Anniversary.mp3', 1400),
  ('Heat Waves', artist_uuid, (SELECT id FROM genres WHERE name = 'Indie'), 240, 'Heat_Waves.mp3', 5000),
  ('Heather', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 200, 'Heather.mp3', 3200),
  ('Heaven Knows I''m Miserable Now', artist_uuid, (SELECT id FROM genres WHERE name = 'Rock'), 175, 'Heaven_Knows_Im_Miserable_Now_2011_Remaster.mp3', 800),
  ('Honeypie', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 165, 'Honeypie.mp3', 700),
  ('I Think They Call This Love', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 195, 'I_Think_They_Call_This_Love_Cover.mp3', 650),
  ('I Wanna Be Yours', artist_uuid, (SELECT id FROM genres WHERE name = 'Rock'), 185, 'I_Wanna_Be_Yours.mp3', 1100),
  ('Ishq Bulaava', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 230, 'Ishq_Bulaava.mp3', 1450),
  ('Jeene Laga Hoon', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 225, 'Jeene_Laga_Hoon.mp3', 1600),
  ('Jo Tum Mere Ho', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 240, 'Jo_Tum_Mere_Ho.mp3', 1800),
  ('Khairiyat', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 260, 'Khairiyat.mp3', 2100),
  ('Kill Bill', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 160, 'Kill_Bill.mp3', 1900),
  ('Line Without a Hook', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 230, 'Line_Without_a_Hook.mp3', 1650),
  ('Love For You', artist_uuid, (SELECT id FROM genres WHERE name = 'R&B'), 180, 'Love_For_You.mp3', 850),
  ('Loverboy', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 195, 'Loverboy.mp3', 920),
  ('Make You Mine', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 215, 'Make_You_Mine.mp3', 1400),
  ('Moonlight', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 190, 'Moonlight.mp3', 1150),
  ('Mount Everest', artist_uuid, (SELECT id FROM genres WHERE name = 'Electronic'), 175, 'Mount_Everest.mp3', 900),
  ('My Kind of Woman', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 195, 'My_Kind_of_Woman.mp3', 1050),
  ('My Oh My', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 180, 'My_Oh_My_feat_DaBaby.mp3', 1250),
  ('Night Changes', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 220, 'Night_Changes.mp3', 1750),
  ('Nothing''s Gonna Hurt You Baby', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 270, 'Nothings_Gonna_Hurt_You_Baby.mp3', 1550),
  ('Nothing''s New', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 205, 'Nothings_New.mp3', 800),
  ('O Meri Laila', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 240, 'O_Meri_Laila.mp3', 950),
  ('Paro', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 120, 'Paro.mp3', 500),
  ('Pink Matter', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 260, 'Pink_Matter.mp3', 1100),
  ('Please, Please, Please', artist_uuid, (SELECT id FROM genres WHERE name = 'Rock'), 140, 'Please_Please_Please_Let_Me_Get_What_I_Want_2011_Remaster.mp3', 700),
  ('Raanjhanaa', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 250, 'Raanjhanaa_From_Raanjhanaa.mp3', 1850),
  ('Renegade', artist_uuid, (SELECT id FROM genres WHERE name = 'Rock'), 215, 'Renegade.mp3', 1000),
  ('Ride Or Die', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 170, 'Ride_Or_Die_Pt_2_with_Villano_Antillano_Tokischa.mp3', 750),
  ('Robbers', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 60, 'Robbers.mp3', 400),
  ('Sahiba', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 195, 'Sahiba.mp3', 1300),
  ('Sanam Re', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 280, 'Sanam_Re.mp3', 1650),
  ('Say Yes To Heaven', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 205, 'Say_Yes_To_Heaven.mp3', 2800),
  ('Sex, Drugs, Etc', artist_uuid, (SELECT id FROM genres WHERE name = 'Rock'), 200, 'Sex_Drugs_Etc.mp3', 900),
  ('Shameless', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 215, 'Shameless.mp3', 850),
  ('Shayad', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 240, 'Shayad.mp3', 1500),
  ('Shut up My Moms Calling', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 175, 'Shut_up_My_Moms_Calling.mp3', 1200),
  ('Softcore', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 205, 'Softcore.mp3', 950),
  ('Somebody Come Through', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 230, 'Somebody_Come_Through.mp3', 750),
  ('Something About You', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 175, 'Something_About_You.mp3', 1100),
  ('Something Just Like This', artist_uuid, (SELECT id FROM genres WHERE name = 'Electronic'), 245, 'Something_Just_Like_This.mp3', 3500),
  ('Stereo Hearts', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 220, 'Stereo_Hearts_feat_Adam_Levine.mp3', 2000),
  ('Sway', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 190, 'Sway.mp3', 850),
  ('Sweater Weather', artist_uuid, (SELECT id FROM genres WHERE name = 'Indie'), 240, 'Sweater_Weather.mp3', 2200),
  ('Sweet', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 280, 'Sweet.mp3', 1300),
  ('Teenage Dream', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 185, 'Teenage_Dream.mp3', 1700),
  ('Tere Bina', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 290, 'Tere_Bina.mp3', 1450),
  ('There Is a Light That Never Goes Out', artist_uuid, (SELECT id FROM genres WHERE name = 'Rock'), 250, 'There_Is_a_Light_That_Never_Goes_Out_2011_Remaster.mp3', 1200),
  ('This Charming Man', artist_uuid, (SELECT id FROM genres WHERE name = 'Rock'), 170, 'This_Charming_Man_2011_Remaster.mp3', 950),
  ('Those Eyes', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 215, 'Those_Eyes.mp3', 1650),
  ('Touch', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 270, 'Touch.mp3', 1400),
  ('Tum Hi Ho', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 250, 'Tum_Hi_Ho.mp3', 2500),
  ('Under The Influence', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 195, 'Under_The_Influence.mp3', 1800),
  ('Until I Found You', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 180, 'Until_I_Found_You_with_Em_Beihold_Em_Beihold_Version.mp3', 2100),
  ('Water Fountain', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 230, 'Water_Fountain.mp3', 1000),
  ('West Coast', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 255, 'West_Coast.mp3', 1150),
  ('Wine Pon You', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 220, 'Wine_Pon_You_feat_Konshens.mp3', 850),
  ('Woman', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 185, 'Woman.mp3', 1300),
  ('Ye Tune Kya Kiya', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 290, 'Ye_Tune_Kya_Kiya.mp3', 1600),
  ('Yeh Raaten Yeh Mausam', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 215, 'Yeh_Raaten_Yeh_Mausam.mp3', 900),
  ('Young And Beautiful', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 240, 'Young_And_Beautiful.mp3', 2800),
  ('Zaalima', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 280, 'Zaalima.mp3', 1450),
  ('a thousand years', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 280, 'a_thousand_years.mp3', 3200),
  ('eyes don''t lie', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 170, 'eyes_dont_lie.mp3', 800),
  ('golden hour', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 210, 'golden_hour.mp3', 1900),
  ('her', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 180, 'her.mp3', 1100),
  ('i''m yours', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 165, 'im_yours.mp3', 1650),
  ('older', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 160, 'older.mp3', 750),
  ('this is what falling in love feels like', artist_uuid, (SELECT id FROM genres WHERE name = 'Pop'), 155, 'this_is_what_falling_in_love_feels_like.mp3', 950),
  ('we fell in love in october', artist_uuid, (SELECT id FROM genres WHERE name = 'Indie'), 190, 'we_fell_in_love_in_october.mp3', 1750)
  ON CONFLICT DO NOTHING;
END $$;
